spring.application.name=AuthService
app.security.jwt.access-token-ttl=10m
app.security.jwt.refresh-token-ttl=7d

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.application.name=Backend
spring.jpa.show-sql=true
