spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

polygon.api.key=${POLYGON_KEY}
polygon.api.secret=${POLYGON_SECRET}


# ????? ? docker-compose.yml ????? ????? ?? ?????????? ??? ???
#backend:
#build: ./backend
#ports:
#- "8080:8080"
#environment:
#SPRING_PROFILES_ACTIVE: prod
#DB_URL: jdbc:postgresql://postgres:5432/codzilla
#DB_USERNAME: user
#DB_PASSWORD: password
#depends_on:
#- postgres
#- judge0-server