spring.application.name=Backend

app.security.jwt.access-token-ttl=10m
app.security.jwt.refresh-token-ttl=7d

app.s3.endpoint=http://localhost:9000
app.s3.access-key=minio-user
app.s3.secret-key=minio-password
app.s3.region=us-east-1
app.s3.bucket-name=codzilla

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://localhost:5433/testingdb
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis-password

logging.level.org.springframework.security=DEBUG
