spring.application.name=Backend
spring.jpa.hibernate.ddl-auto=update

app.security.jwt.access-token-ttl=10m
app.security.jwt.refresh-token-ttl=7d

app.s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
app.s3.access-key=${S3_ACCESS_KEY}
app.s3.secret-key=${S3_PASSWORD}
app.s3.region=${S3_REGION}
app.s3.bucket-name=${S3_BUCKET_NAME}

app.match.time-to-pick=20s
app.match.websocket-match-prefix=/topic/match/

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/testingdb}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:secret}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:redis-password}

judge0.base-url=${JUDGE0_BASE_URL:http://localhost:2358}

artefactik0.base-url=${ARTEFACTIK0_BASE_URL:http://localhost:8081}
sqlservice.base-url=${SQLSERVICE_BASE_URL:http://localhost:8082}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket=TRACE